### PR TITLE
Show media attachments for admins

### LINKED ISSUE #57: Attached media files don't appear on lesson pages for admins
Attached media files don't appear on Lesson pages.

#### Steps to Reproduce
1. Add some media file on the Lesson Media panel of any Lesson page.
2. Publish.
3. Look at it on the front page.

#### What I Expected
Media files should listed under the content of the lesson.

#### What Happened Instead
No media file listing appears.

#### PHP / WordPress / Sensei version
WordPress 5.1.1.
Sensei 1.12.3, Sensei 2.0.0. and Sensei LMS 2.0.1.
Sensei Media Attachments 1.0.2 and 2.0.0

### PR DESCRIPTION
**Pull request by yscik**
Fixes #57

#### Changes proposed in this Pull Request:

* Show media attachments on lesson/course frontend for users with **edit_courses** cap

#### Testing instructions:

* Admins/teachers should now see the attached files, without having to be enrolled in the course. 

#### Proposed changelog entry for your changes:

* Show media attachments to users who can 'edit_courses'.

### CODE REVIEW

File: classes/class-sensei-media-attachments.php [hunk 1]
```diff
@@ -183,7 +183,7 @@ public function display_attached_media() {
 
 		$user_id    = get_current_user_id();
 		$course_id  = 'course' === $post_type ? $post->ID : get_post_meta( $post->ID, '_lesson_course', true );
-		$show_links = Sensei_Utils::user_started_course( $course_id, $user_id );
+		$show_links = Sensei_Utils::user_started_course( $course_id, $user_id ) || current_user_can( 'edit_courses' );
```
Comment (donnapep) [inline classes/class-sensei-media-attachments.php]: Adding this cap means teachers will be able to view media attachments for courses they are not assigned to. They should only be able to view media for courses where they are the assigned teacher.
